FROM eclipse-temurin:25-jdk-alpine

RUN apk upgrade --no-cache libexpat expat p11-kit p11-kit-trust && \
    apk add --no-cache mesa-gl libxcb libxi libxrender libxrandr libxcursor libxinerama

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle gradle.properties ./

RUN chmod +x gradlew && ./gradlew dependencies --no-daemon || true

CMD ["/bin/sh"]
