name: lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  detekt:
    name: detekt
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6.3.0
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: run detekt
        run: ./gradlew detekt --no-daemon --stacktrace
      - name: capture detekt report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: detekt-report
          if-no-files-found: ignore
          path: build/reports/detekt/
